spring:
  datasource:
    url: jdbc:h2:./synct;
    username: admin
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true


# Secrets are stored in a separate configuration file called application-secrets.yaml. This is included as part of the deployment or development cycle.
# Secrets are defined as blank here to keep track of what is required.
secrets:
  trakt:
    api-key:
