spring:
  datasource:
    url: jdbc:h2:./synct;
    username: admin
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
